#!/usr/bin/env node

/**
 * AiAdminBot Interactive Setup Wizard
 * Guides users through configuring their bot with a friendly step-by-step process.
 * Works both for source installs and .exe builds.
 *
 * Usage: node src/setup-wizard.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(question) {
  return new Promise(resolve => rl.question(question, resolve));
}

function clear() {
  process.stdout.write('\x1Bc');
}

function banner() {
  console.log('');
  console.log('  ╔══════════════════════════════════════════╗');
  console.log('  ║     🛡️  AiAdminBot — Setup Wizard          ║');
  console.log('  ║     AI-Powered Discord Administration    ║');
  console.log('  ╚══════════════════════════════════════════╝');
  console.log('');
}

function success(msg) {
  console.log(`  ✅ ${msg}`);
}

function info(msg) {
  console.log(`  ℹ️  ${msg}`);
}

function warn(msg) {
  console.log(`  ⚠️  ${msg}`);
}

// Determine paths (works for both source and pkg exe)
function getBasePath() {
  // When running as a pkg exe, process.pkg is defined
  if (process.pkg) {
    return path.dirname(process.execPath);
  }
  return path.join(__dirname, '..');
}

async function run() {
  clear();
  banner();

  const basePath = getBasePath();
  const envPath = path.join(basePath, '.env');
  const envExamplePath = path.join(basePath, '.env.example');

  console.log('  Welcome! This wizard will help you set up AiAdminBot.');
  console.log('  You\'ll need a few things ready:');
  console.log('');
  console.log('    1. A Discord Bot token (from Discord Developer Portal)');
  console.log('    2. (Optional) An OpenRouter API key for AI features');
  console.log('');

  // Check if .env already exists
  if (fs.existsSync(envPath)) {
    const overwrite = await ask('  A .env file already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      info('Keeping existing .env file. Setup cancelled.');
      rl.close();
      return;
    }
  }

  console.log('');
  console.log('  ── Step 1: Discord Bot Credentials ──────────────────');
  console.log('');
  info('Create a bot at: https://discord.com/developers/applications');
  console.log('');

  const discordToken = await ask('  Discord Bot Token: ');
  if (!discordToken || discordToken.trim().length < 20) {
    warn('Token looks invalid. You can edit .env manually later.');
  }

  console.log('');
  console.log('  ── Step 2: Language ─────────────────────────────────');
  console.log('');
  console.log('  Supported languages:');
  console.log('    tr = 🇹🇷 Türkçe    en = 🇬🇧 English');
  console.log('    de = 🇩🇪 Deutsch    es = 🇪🇸 Español');
  console.log('    fr = 🇫🇷 Français   pt = 🇧🇷 Português');
  console.log('    ru = 🇷🇺 Русский    ar = 🇸🇦 العربية');
  console.log('');

  let locale = await ask('  Language code (default: tr): ');
  locale = locale.trim().toLowerCase() || 'tr';
  const validLocales = ['tr', 'en', 'de', 'es', 'fr', 'pt', 'ru', 'ar'];
  if (!validLocales.includes(locale)) {
    warn(`Unknown locale "${locale}". Defaulting to "tr".`);
    locale = 'tr';
  }

  console.log('');
  console.log('  ── Step 3: AI Features (Optional) ──────────────────');
  console.log('');
  info('AI features are free via OpenRouter. Get a key at: https://openrouter.ai/keys');
  console.log('');

  const openrouterKey = await ask('  OpenRouter API Key (press Enter to skip): ');
  let aiChatEnabled = false;
  let aiModEnabled = false;

  if (openrouterKey && openrouterKey.trim().length > 10) {
    const enableChat = await ask('  Enable AI Chat Assistant? (Y/n): ');
    aiChatEnabled = enableChat.toLowerCase() !== 'n';

    const enableMod = await ask('  Enable AI Smart Moderation? (Y/n): ');
    aiModEnabled = enableMod.toLowerCase() !== 'n';
  } else {
    info('Skipping AI features. You can enable them later in .env');
  }

  // Build .env content
  const envContent = `# AiAdminBot Configuration
# Generated by Setup Wizard

# Discord Bot Credentials
DISCORD_TOKEN=${discordToken.trim()}

# Database
DATABASE_PATH=./data/bot.db

# Language: tr, en, de, es, fr, pt, ru, ar
LOCALE=${locale}

# Logging
LOG_LEVEL=info

# AI Features (OpenRouter - Free Models)
OPENROUTER_API_KEY=${openrouterKey.trim() || 'your_openrouter_key_here'}
AI_MODEL=openrouter/free
AI_CHAT_ENABLED=${aiChatEnabled}
AI_CHAT_CHANNEL=ai-chat
AI_CHAT_RATE_LIMIT=5
AI_MODERATION_ENABLED=${aiModEnabled}
AI_MOD_CONFIDENCE_THRESHOLD=0.8
`;

  // Write .env
  fs.writeFileSync(envPath, envContent);
  success('.env file created!');

  // Copy example configs if they don't exist
  const configDir = path.join(basePath, 'config');
  const configFiles = [
    { example: 'config.example.json', target: 'config.json' },
    { example: 'server-setup.example.json', target: 'server-setup.json' },
    { example: 'role-menus.example.json', target: 'role-menus.json' },
  ];

  for (const { example, target } of configFiles) {
    const exampleFile = path.join(configDir, example);
    const targetFile = path.join(configDir, target);

    if (!fs.existsSync(targetFile) && fs.existsSync(exampleFile)) {
      fs.copyFileSync(exampleFile, targetFile);
      success(`Created config/${target} from example`);
    }
  }

  // Create data directory if it doesn't exist
  const dataDir = path.join(basePath, 'data');
  if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
    success('Created data/ directory');
  }

  console.log('');
  console.log('  ── Setup Complete! ──────────────────────────────────');
  console.log('');
  console.log('  Next steps:');
  console.log('');

  if (process.pkg) {
    // Running as exe
    console.log('    1. Close this window');
    console.log('    2. Run AiAdminBot.exe again to start the bot');
    console.log('    3. Use /ai-setup in Discord to set up your server');
  } else {
    // Running from source
    console.log('    1. Deploy commands:  npm run deploy');
    console.log('    2. Start the bot:    npm start');
    console.log('    3. Use /ai-setup in Discord to set up your server');
  }

  console.log('');
  info('Edit .env anytime to change settings.');
  info('Docs: https://github.com/HaydarOzturk/AiAdminBot');
  console.log('');

  rl.close();
}

run().catch(err => {
  console.error('Setup failed:', err.message);
  rl.close();
  process.exit(1);
});
